CREATE TABLE IF NOT EXISTS languages (
  id   SERIAL       PRIMARY KEY,
  code VARCHAR(2)   UNIQUE,
  name VARCHAR(100) NOT NULL
);

INSERT INTO languages (
  code,
  name
) VALUES
  ('en', 'English'),
  ('es', 'Spanish'),
  ('zh', 'Mandarin Chinese'),
  ('hi', 'Hindi'),
  ('ar', 'Arabic'),
  ('bn', 'Bengali'),
  ('ru', 'Russian'),
  ('pt', 'Portuguese'),
  ('id', 'Indonesian'),
  ('ur', 'Urdu'),
  ('fr', 'French'),
  ('de', 'German'),
  ('ja', 'Japanese'),
  ('sw', 'Swahili'),
  ('te', 'Telugu'),
  ('mr', 'Marathi'),
  ('ta', 'Tamil'),
  ('tr', 'Turkish'),
  ('it', 'Italian'),
  ('vi', 'Vietnamese'),
  ('ko', 'Korean'),
  ('pl', 'Polish'),
  ('uk', 'Ukrainian'),
  ('ms', 'Malay'),
  ('ps', 'Pashto'),
  ('kn', 'Kannada'),
  ('or', 'Odia'),
  ('am', 'Amharic'),
  ('az', 'Azerbaijani'),
  ('my', 'Burmese'),
  ('fil', 'Filipino'),
  ('yo', 'Yoruba'),
  ('ig', 'Igbo'),
  ('ku', 'Kurdish'),
  ('mai', 'Maithili'),
  ('sd', 'Sindhi'),
  ('ha', 'Hausa'),
  ('th', 'Thai'),
  ('nl', 'Dutch'),
  ('km', 'Khmer'),
  ('yue', 'Cantonese'),
  ('sv', 'Swedish'),
  ('fa', 'Persian'),
  ('ro', 'Romanian'),
  ('el', 'Greek'),
  ('cs', 'Czech'),
  ('hu', 'Hungarian'),
  ('be', 'Belarusian'),
  ('so', 'Somali'),
  ('he', 'Hebrew'
  );
