CREATE TABLE IF NOT EXISTS locations (
  id               SERIAL        PRIMARY KEY,
  address_line_one VARCHAR(400)             ,
  address_line_two VARCHAR(3000)            ,
  city             VARCHAR(100)             ,
  province         VARCHAR(100)             ,
  country          VARCHAR(100)             ,
  postal_code      VARCHAR(100)             ,
  neighbourhood    VARCHAR(100)
);

INSERT INTO locations (
  address_line_one,
  address_line_two,
  city,
  province,
  country,
  postal_code,
  neighbourhood
)
VALUES
(1, '123 Main St', NULL, 'Toronto', 'Ontario', 'Canada', 'M5B 2H1',
  'Downtown'),
(2, '456 Queen St', NULL, 'Toronto', 'Ontario', 'Canada', 'M5V 2B4',
  'Fashion District'),
(3, '789 King St', NULL, 'Toronto', 'Ontario', 'Canada', 'M5V 1M3',
  'Entertainment District'),
(4, '321 Bloor St', NULL, 'Toronto', 'Ontario', 'Canada', 'M4W 1A9',
  'Yorkville'),
(5, '654 Dundas St', NULL, 'Toronto', 'Ontario', 'Canada', 'M5T 1H3',
  'Chinatown'),
(6, '987 College St', NULL, 'Toronto', 'Ontario', 'Canada', 'M6H 1A6',
  'Little Italy'),
(7, '147 Yonge St', NULL, 'Toronto', 'Ontario', 'Canada', 'M5C 1W6',
  'Financial District'),
(8, '258 Bay St', NULL, 'Toronto', 'Ontario', 'Canada', 'M5J 2R8',
  'Harbourfront'),
(9, '369 Adelaide St', NULL, 'Toronto', 'Ontario', 'Canada', 'M5V 1S4',
  'Fashion District'),
(10, '963 Richmond St', NULL, 'Toronto', 'Ontario', 'Canada', 'M5V 1X5',
  'Queen West'),
(11, '111 Spadina Ave', NULL, 'Toronto', 'Ontario', 'Canada', 'M5V 2K2',
  'Chinatown'),
(12, '222 Front St W', NULL, 'Toronto', 'Ontario', 'Canada', 'M5V 3M1',
  'Financial District'),
(13, '333 Wellesley St E', NULL, 'Toronto', 'Ontario', 'Canada', 'M4X 1H2',
  'Cabbagetown'),
(14, '444 Roncesvalles Ave', NULL, 'Toronto', 'Ontario', 'Canada', 'M6R 2N1',
  'Roncesvalles'),
(15, '555 University Ave', NULL, 'Toronto', 'Ontario', 'Canada', 'M5G 1X8',
  'Discovery District'),
(16, '666 Bathurst St', NULL, 'Toronto', 'Ontario', 'Canada', 'M5S 2R1',
  'The Annex'),
(17, '777 Jarvis St', NULL, 'Toronto', 'Ontario', 'Canada', 'M4Y 2G6',
  'Church and Wellesley'),
(18, '1198 Queen St W', NULL, 'Toronto', 'Ontario', 'Canada', 'M6J 1J6',
  'Queen Street West'),
(19, '555 King St W', NULL, 'Toronto', 'Ontario', 'Canada', 'M5V 1M1',
  'Entertainment District'),
(20, '379 Harbord St', NULL, 'Toronto', 'Ontario', 'Canada', 'M6G 1H8',
  'Harbord Village'),
(21, '199 Augusta Ave', NULL, 'Toronto', 'Ontario', 'Canada', 'M5T 2L4',
  'Kensington Market'),
(22, '1320 Queen St W', NULL, 'Toronto', 'Ontario', 'Canada', 'M6K 1L4',
  'Parkdale'),
(23, '860 The Queensway', NULL, 'Toronto', 'Ontario', 'Canada', 'M8Z 1N7',
  'Etobicoke'),
(24, '18 Dupont St', NULL, 'Toronto', 'Ontario', 'Canada', 'M5R 1V2',
  'Yorkville'),
(25, '111C Queen St E', NULL, 'Toronto', 'Ontario', 'Canada', 'M5C 1S2',
  'Old Town'),
(26, '1454 Dundas St W', NULL, 'Toronto', 'Ontario', 'Canada', 'M6J 1Y6',
  'Little Portugal'),
(27, '101 Portland St', NULL, 'Toronto', 'Ontario', 'Canada', 'M5V 2N3',
  'Fashion District'),
(28, '1 Benvenuto Pl', NULL, 'Toronto', 'Ontario', 'Canada', 'M4V 2L1',
  'Midtown Toronto'),
(29, '227 Ossington Ave', NULL, 'Toronto', 'Ontario', 'Canada', 'M6J 2Z8',
  'West Queen West'),
(30, '133 Richmond St W', NULL, 'Toronto', 'Ontario', 'Canada', 'M5H 2L3',
  'Financial District'),
(31, '163 Spadina Ave', NULL, 'Toronto', 'Ontario', 'Canada', 'M5V 2L6',
  'Chinatown'),
(32, '971 Ossington Ave', NULL, 'Toronto', 'Ontario', 'Canada', 'M6G 3V5',
  'Davenport'),
(33, '501 College St', NULL, 'Toronto', 'Ontario', 'Canada', 'M6G 1A5',
  'Little Italy');
