CREATE TABLE IF NOT EXISTS locations (
  id               SERIAL        PRIMARY KEY,
  address_line_one VARCHAR(400)             ,
  address_line_two VARCHAR(3000)            ,
  city             VARCHAR(100)             ,
  province         VARCHAR(100)             ,
  country          VARCHAR(100)             ,
  postal_code      VARCHAR(100)             ,
  neighbourhood    VARCHAR(100)
);

INSERT INTO locations (
  id,
  address_line_one,
  address_line_two,
  city,
  province,
  country,
  postal_code,
  neighbourhood
)
VALUES
(1, '2015 Avenue Rd', NULL, 'North York', 'ON', 'Canada', 'M5M 4A5',
  'Cricket Club'),
(2, '150 York St', NULL, 'Toronto', 'ON', 'Canada', 'M5H 3S5',
  'Financial District'),
(3, '222 Richmond St W', NULL, 'Toronto', 'ON', 'Canada', 'M5V 1V6',
  'Entertainment District'),
(4, '100 Cumberland St', NULL, 'Toronto', 'ON', 'Canada', 'M5R 1A6',
  'Yorkville'),
(5, '654 Dundas St', NULL, 'Toronto', 'ON', 'Canada', 'M5T 1H3',
  'Chinatown'),
(6, '3220 Yonge St', NULL, 'Toronto', 'ON', 'Canada', 'M4N 2L2',
  'Yonge and Lawrence'),
(7, '2373 Yonge St', NULL, 'Toronto', 'ON', 'Canada', 'M4P 2C8',
  'Yonge–Eglinton'),
(8, '60 Yorkville Ave', NULL, 'Toronto', 'ON', 'Canada', 'M4W 0A4',
  'Yorkville'),
(9, '10 Bay St.', '#105', 'Toronto', 'ON', 'Canada', 'M5J 2R8',
  'Harbourfront'),
(10, '505 College St', NULL, 'Toronto', 'ON', 'Canada', 'M6J 2J3',
  'Little Italy'),
(11, '1 Richmond St W', NULL, 'Toronto', 'ON', 'Canada', 'M5H 3W4',
  'Financial District'),
(12, '222 Front St W', NULL, 'Toronto', 'ON', 'Canada', 'M5V 3M1',
  'Financial District'),
(13, '333 Wellesley St E', NULL, 'Toronto', 'ON', 'Canada', 'M4X 1H2',
  'Cabbagetown'),
(14, '444 Roncesvalles Ave', NULL, 'Toronto', 'ON', 'Canada', 'M6R 2N1',
  'Roncesvalles'),
(15, '555 University Ave', NULL, 'Toronto', 'ON', 'Canada', 'M5G 1X8',
  'Discovery District'),
(16, '666 Bathurst St', NULL, 'Toronto', 'ON', 'Canada', 'M5S 2R1',
  'The Annex'),
(17, '777 Jarvis St', NULL, 'Toronto', 'ON', 'Canada', 'M4Y 2G6',
  'Church and Wellesley'),
(18, '1198 Queen St W', NULL, 'Toronto', 'ON', 'Canada', 'M6J 1J6',
  'Queen Street West'),
(19, '555 King St W', NULL, 'Toronto', 'ON', 'Canada', 'M5V 1M1',
  'Entertainment District'),
(20, '379 Harbord St', NULL, 'Toronto', 'ON', 'Canada', 'M6G 1H8',
  'Harbord Village'),
(21, '199 Augusta Ave', NULL, 'Toronto', 'ON', 'Canada', 'M5T 2L4',
  'Kensington Market'),
(22, '1320 Queen St W', NULL, 'Toronto', 'ON', 'Canada', 'M6K 1L4',
  'Parkdale'),
(23, '860 The Queensway', NULL, 'Toronto', 'ON', 'Canada', 'M8Z 1N7',
  'Etobicoke'),
(24, '18 Dupont St', NULL, 'Toronto', 'ON', 'Canada', 'M5R 1V2',
  'Yorkville'),
(25, '111C Queen St E', NULL, 'Toronto', 'ON', 'Canada', 'M5C 1S2',
  'Old Town'),
(26, '1454 Dundas St W', NULL, 'Toronto', 'ON', 'Canada', 'M6J 1Y6',
  'Little Portugal'),
(27, '101 Portland St', NULL, 'Toronto', 'ON', 'Canada', 'M5V 2N3',
  'Fashion District'),
(28, '1 Benvenuto Pl', NULL, 'Toronto', 'ON', 'Canada', 'M4V 2L1',
  'Midtown Toronto'),
(29, '227 Ossington Ave', NULL, 'Toronto', 'ON', 'Canada', 'M6J 2Z8',
  'West Queen West'),
(30, '133 Richmond St W', NULL, 'Toronto', 'ON', 'Canada', 'M5H 2L3',
  'Financial District'),
(31, '163 Spadina Ave', '1st Floor', 'Toronto', 'ON', 'Canada', 'M5V 2A5',
  'Chinatown'),
(32, '971 Ossington Ave', NULL, 'Toronto', 'ON', 'Canada', 'M6G 3V5',
  'Davenport'),
(33, '501 College St', NULL, 'Toronto', 'ON', 'Canada', 'M6G 1A5',
  'Little Italy'),
(34, '162 Danforth Ave', NULL, 'Toronto', 'ON', 'Canada', 'M4K 1N1',
  'Playter Estates'),
(35, '545 King St W', 'Floor 1, iQ Offices', 'Toronto', 'ON', 'M5V 1M1',
  'Wellington Place'),
(36, '1 Harbour Square', '38th Floor', 'Toronto', 'ON', 'Canada',
  'M5J 1A6', 'Harbourfront'),
(37, '51 Camden St', 'Lower level of the Ace Hotel', 'Toronto', 'ON', 'Canada',
  'M5V 1V2', 'Fashion District'),
(38, '130 King St W', Null, 'Toronto', 'ON', 'Canada', 'M5X 2A2',
  'Financial District'),
(39, '1256 St Clair Ave W', Null, 'Toronto', 'ON', 'Canada', 'M6E 1B9',
  'Earlscourt'),
(40, '67 Richmond St W', Null, 'Toronto', 'ON', 'Canada', 'M5H 1Z5',
  'Financial District');
