CREATE TABLE IF NOT EXISTS user_email_update_requests (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL,
  new_email VARCHAR(255) NOT NULL,
  token VARCHAR(255) UNIQUE NOT NULL,
  token_created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
  token_expires_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC') + INTERVAL '48 hours',
  resend_count INTEGER DEFAULT 0,
  FOREIGN KEY (user_id) REFERENCES users (id)
);
